PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

SELECT ?winner1 ?winner2 ?country
WHERE {
  ?npl1 a :NobelPrizeLiterature ; :winner ?winner1 .
  ?npl2 a :NobelPrizeLiterature ; :winner ?winner2 .
  ?winner1 :country ?country .
  ?winner2 :country ?country .
}