PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

SELECT *
FROM :G-FPW
FROM :G-SP
FROM NAMED :G-SP
FROM NAMED :G-TM
FROM NAMED :G-BB
FROM NAMED :G-FM
FROM NAMED :G-JE
WHERE { 
  GRAPH ?g { 
    ?prize :winner ?winner .
  } 
  OPTIONAL {
    ?war :combatant ?winner .
    ?country :war ?war .
    ?winner :country ?country .
  }
}