PREFIX : <http://ex.org/>
SELECT ?nplWinner ?nplYear ?warEndYear
WHERE {
  ?npl a :NobelPrizeLiterature ; :year ?nplYear ; :winner ?nplWinner .
  ?war :combatant ?nplWinner ; :end ?warEndYear .
}