PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

SELECT (coalesce(?lFr,?lEs,?lEn) AS ?l)
WHERE {
  ?prize :winner :SPrudhomme ; a ?type .
  OPTIONAL { 
    ?type rdfs:label ?lEn . 
    FILTER (langMatches(lang(?lEn),"en")) 
  }
  OPTIONAL { 
    ?type rdfs:label ?lEs . 
    FILTER (langMatches(lang(?lEs),"es")) 
  }
  OPTIONAL { 
    ?type rdfs:label ?lFr . 
    FILTER (langMatches(lang(?lFr),"fr")) 
  }  
}