PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

DELETE { ?prize2 :prev ?prize1 }
INSERT { ?prize1 :next ?prize2 }
WHERE  { 
  { ?prize1 :next ?prize2 }
  UNION 
  { ?prize2 :prev ?prize1 }
}