PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

SELECT ?family (count(distinct ?winner) AS ?num)
WHERE {
  ?npl a :NobelPrizeLiterature ; :winner ?winner .
  ?winner :country ?country .
  VALUES (?country ?family) {
    (:France :Romance)
    (:France :Celtic)    
    (:Spain :Romance)
    (:Norway :Germanic)
    (:Germany :Germanic)    
  }
}
GROUP BY ?family