PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

CONSTRUCT {
  ?w1a :succ ?w2 .
  ?w2 :pred ?w1a .
  ?w1b :shared ?w1c .
}
WHERE {
  ?npl1 a :NobelPrizeLiterature ; :winner ?w1a .
  OPTIONAL {
    ?npl2 a :NobelPrizeLiterature ; :winner ?w2 .
    ?npl1 :next ?npl2 .
  } 
  OPTIONAL {
    ?npl1 :winner ?w1b , ?w1c . FILTER(?w1b != ?w1c)
  }
}