PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/>

SELECT ?winner
WHERE {
  ?npl a :NobelPrizeLiterature ; :winner ?winner ; :year ?year .
  MINUS {
    ?ntm a :NobelPrizeLiterature ; :winner :TMommsen ; :year ?ytm .
    FILTER (xsd:integer(str(?year)) > xsd:integer(str(?ytm)))
  }
}