PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

SELECT ?winner
WHERE {
  {
    SELECT ?winner (count(?winner2) AS ?num)
    WHERE {
      ?npl a :NobelPrizeLiterature ; :winner ?winner .
      ?npl :prev+ ?npl2 .
      ?npl2 :winner ?winner2 .
    }
    GROUP BY ?winner
  } 
  {
    SELECT ?winner (count(?winner2) AS ?num)
    WHERE {
      ?npl a :NobelPrizeLiterature ; :winner ?winner .
      ?npl :next+ ?npl2 .
      ?npl2 :winner ?winner2 .
    }
    GROUP BY ?winner
  }
}