PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

SELECT ?winner
WHERE { 
  { ?w :combatant ?pw } UNION { GRAPH ?g { ?w :combatant ?pw } }
  { ?p :winner ?pw } UNION { GRAPH ?g { ?p :winner ?pw } }
  { ?p a :NobelPrizeLiterature } UNION 
    { GRAPH ?g { ?p a :NobelPrizeLiterature } }
}