PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://ex.org/> 

SELECT ?w1 ?w2
WHERE {
  ?np1 a/rdfs:subClassOf* :NobelPrize  ; ?winner ?w1 .
  ?np2 a/rdfs:subClassOf* :NobelPrize  ; ?winner ?w2 . 
  ?np1 :next* ?np2 .
  ?w1 :country ?c . 
  ?w2 :country ?c .
  FILTER (?w1 != ?w2)
  FILTER NOT EXISTS {
    ?np a/rdfs:subClassOf* :NobelPrize  ; ?winner ?w .
    ?w :country ?c .
    ?np :prev+ ?np1 .
    ?np :next+ ?np2 .
  }
}